"""Fresh, parallel re-harvest of an EXISTING corpus's samples (round-3
CRITICAL fix, see `crucible.latent.harvest`'s module docstring and
`.superpowers/sdd/2026-08-26-crucible-pillar1-blite/minority-pass-report.md`).

Every `samples.jsonl` produced before the round-3 fix (a corpus generated by
`generate_corpus`, then possibly enriched by `generate_minority_inputs` /
`generate_battery_inputs`, ALL of which share one scratch directory across
thousands of `harvest()` calls) is suspect: `harvest()` used fixed sensorium
run-ids ("run-a"/"run-b") and never checked its subprocess's exit code, so
every call after the first one to touch a given scratch directory silently
replayed the FIRST call's result -- confirmed against production data
(`runs/blite-corpus/samples.jsonl`'s 1000 rows were all byte-identical). This
module does not try to salvage anything from that file; it re-runs every
(function, input) pair `functions.jsonl` ever recorded, from scratch, against
the FIXED `harvest()`, and replaces `samples.jsonl` entirely -- archiving the
old one first, as evidence, never deleting it.

Parallel, not sequential: `harvest()` is subprocess-bound and, post-fix,
fully isolated per call (its own `call-<uuid>` scratch subdirectory), so many
calls may run concurrently against ONE shared `corpus_dir` scratch directory
safely. `reharvest_samples` drives that with a `ThreadPoolExecutor(jobs)` --
every `harvest()` call itself runs unlocked (it is the expensive, I/O- and
subprocess-bound step), and only the balance-guard check, the running
`class_counts`, and the `samples.jsonl` write are serialized under one
`threading.Lock` (see `_reharvest_one`). The balance guard is REBUILT FROM
ZERO here (unlike `generate_minority_inputs`/`generate_battery_inputs`, which
seed it from the corpus's real existing balance) -- there is no trustworthy
existing balance to seed from; that is the entire reason this module exists.

Reuses `crucible.latent.gen`'s pure, stateless pieces rather than duplicating
them: `binary_label`, `_balance_guard_rejects`, `_snapshot_to_json`, and
`_dump_stats_json` (the shared stats-file serialization every pass in this
package delegates to). It does NOT reuse `_harvest_and_write_samples` /
`_harvest_and_write_minority_samples` -- neither is thread-safe (no locking
around their `class_counts`/file-write mutations), and wrapping either
call ENTIRELY in a lock would serialize the expensive `harvest()` step too,
defeating the point of `jobs > 1`.
"""
from __future__ import annotations

import json
import shutil
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Callable

from crucible.latent import gen
from crucible.latent.harvest import HarvestError, harvest

# Live-visibility knob, same role as gen.py's GEN_STATS_FLUSH_INTERVAL /
# MINORITY_STATS_FLUSH_INTERVAL / gen_battery.py's BATTERY_STATS_FLUSH_
# INTERVAL -- an ops/UX cadence, not a prereg-cited number, kept local here
# (not config.py) and directly monkeypatchable. Counted in COMPLETED work
# items (harvest calls finishing), not functions -- reharvest's unit of work
# is one (function, args) pair, not one function.
REHARVEST_STATS_FLUSH_INTERVAL = 100


def reharvest_samples(
    corpus_dir: Path, *, jobs: int = 8, log: Callable[[str], None] = print,
) -> dict:
    """Re-harvest every (function, input) pair in `corpus_dir/functions.jsonl`
    from scratch, replacing `samples.jsonl` entirely.

    Steps:

    1. If `samples.jsonl` already exists, it is copied (never moved -- the
       original stays right where it was, in case anything else is mid-read
       of it) to `samples.jsonl.replay-corrupt` -- evidence of the bug this
       module exists to fix, kept forever. Idempotent against a second
       `reharvest_samples` call over the same `corpus_dir`: if
       `samples.jsonl.replay-corrupt` already exists, it is NEVER
       overwritten -- a second run's `samples.jsonl` (itself the first
       reharvest's OUTPUT, not corrupt) must not clobber the original
       corrupt evidence.
    2. `samples.jsonl` is then opened in TRUNCATE mode -- a genuinely fresh
       file, never appended to the old (corrupt) content.
    3. Every `(fn_id, function_src, args_literal)` triple from
       `functions.jsonl`'s `args_literals` (file order for functions, list
       order within a function) becomes one work item -- `stats["candidates"]`
       is this count, fixed before any harvesting starts.
    4. Work items are harvested via `ThreadPoolExecutor(jobs)`
       (`_reharvest_one`, one call per item): `HarvestError`/`OSError` ->
       `harvest_error`; `result.truncated` -> `truncated_rejected`; not
       `result.deterministic` -> `nondet_rejected`; balance guard
       (`gen._balance_guard_rejects`, evaluated against `class_counts`
       REBUILT FROM ZERO, never seeded from the old file) rejects ->
       `balance_rejected`; otherwise -> written to `samples.jsonl` and
       counted in `accepted_samples`. CONSERVATION (test-enforced): these
       five buckets sum to exactly `stats["candidates"]` once `complete`.
    5. On the success path only, `samples.jsonl` is rewritten with its
       lines SORTED (`_rewrite_samples_sorted`) -- `corpus.build_manifest`
       hashes samples.jsonl's raw file bytes, and the order threads happen
       to finish writing in is not reproducible run to run; sorting the
       raw JSON-line text is what makes `samples_sha256` depend on the
       accepted content alone.

    `reharvest_stats.json` (this function's return value, verbatim, plus
    `"jobs"` and `"complete"`) is flushed every `REHARVEST_STATS_FLUSH_
    INTERVAL` completed work items, and unconditionally in a `finally`
    block -- a crash mid-run still leaves `complete: False` and the real
    counts accumulated so far, same discipline as every other pass in this
    package. Never opens `functions.jsonl` for writing.
    """
    corpus_dir = Path(corpus_dir)
    functions_path = corpus_dir / "functions.jsonl"
    samples_path = corpus_dir / "samples.jsonl"
    corrupt_path = corpus_dir / "samples.jsonl.replay-corrupt"
    stats_path = corpus_dir / "reharvest_stats.json"
    scratch = corpus_dir / "_reharvest_scratch"

    functions = [
        json.loads(line) for line in functions_path.read_text().splitlines() if line.strip()
    ]

    # Archive BEFORE the fresh file is ever opened -- open("w") below would
    # truncate first and there would be nothing left to copy.
    if samples_path.exists() and not corrupt_path.exists():
        shutil.copy2(samples_path, corrupt_path)

    work_items = [
        (fn["fn_id"], fn["function_src"], args_literal)
        for fn in functions
        for args_literal in fn.get("args_literals", ())
    ]

    stats = {
        "jobs": jobs,
        "functions_total": len(functions),
        "candidates": len(work_items),
        "harvest_error": 0,
        "nondet_rejected": 0,
        "truncated_rejected": 0,
        "balance_rejected": 0,
        "accepted_samples": 0,
        "complete": False,
    }
    class_counts = {0: 0, 1: 0}   # rebuilt from zero -- see module docstring
    lock = threading.Lock()

    try:
        with samples_path.open("w") as samples_f, ThreadPoolExecutor(max_workers=jobs) as ex:
            futures = [
                ex.submit(_reharvest_one, fn_id, function_src, args_literal, scratch,
                         samples_f, stats, class_counts, lock)
                for fn_id, function_src, args_literal in work_items
            ]
            for i, fut in enumerate(as_completed(futures), start=1):
                fut.result()   # propagate any bug that isn't HarvestError/OSError
                log(f"reharvest {i}/{len(work_items)}")
                if i % REHARVEST_STATS_FLUSH_INTERVAL == 0:
                    with lock:
                        _write_reharvest_stats(stats_path, stats)
        stats["complete"] = True
        _rewrite_samples_sorted(samples_path)
    finally:
        _write_reharvest_stats(stats_path, stats)
    return stats


def _reharvest_one(
    fn_id: str, function_src: str, args_literal: str, scratch: Path,
    samples_f, stats: dict, class_counts: dict[int, int], lock: threading.Lock,
) -> None:
    """Harvest ONE (function, args) pair, on a worker thread, and -- if it
    survives every filter -- append it to `samples_f`.

    `harvest()` itself runs UNLOCKED: it is subprocess-bound (two `sensorium
    run` calls) and, post the round-3 fix, fully isolated per call, so many
    of these run genuinely concurrently. Only the parts that touch STATE
    SHARED across threads -- `stats`, `class_counts`, and the file -- run
    under `lock`, and only after the expensive work is already done, so the
    lock is held for a dict update and a line write, never for a harvest.
    """
    try:
        result = harvest(function_src, args_literal, scratch)
    except (HarvestError, OSError):
        with lock:
            stats["harvest_error"] += 1
        return

    if result.truncated:
        with lock:
            stats["truncated_rejected"] += 1
        return
    if not result.deterministic:
        with lock:
            stats["nondet_rejected"] += 1
        return

    label = gen.binary_label(result.outcome)
    # Serialized OUTSIDE the lock -- json.dumps touches only this call's own
    # local `result`, never shared state, so there is nothing to protect by
    # doing it while holding the lock.
    row = json.dumps({
        "fn_id": fn_id,
        "function_src": function_src,
        "args": args_literal,
        "outcome": result.outcome,
        "return_repr": result.return_repr,
        "snapshots": [gen._snapshot_to_json(s) for s in result.snapshots],
    })
    with lock:
        if gen._balance_guard_rejects(label, class_counts):
            stats["balance_rejected"] += 1
            return
        class_counts[label] += 1
        stats["accepted_samples"] += 1
        samples_f.write(row + "\n")
        samples_f.flush()


def _write_reharvest_stats(path: Path, stats: dict) -> None:
    """The single reharvest_stats.json write path -- delegates to
    `gen._dump_stats_json` (DRY: identical serialization to every other
    pass's stats file) but kept as its own name so this pass's periodic-
    flush test double can be monkeypatched independently of the other
    passes' own stats writers."""
    gen._dump_stats_json(path, stats)


def _rewrite_samples_sorted(samples_path: Path) -> None:
    """Canonicalize `samples.jsonl`'s on-disk byte order once harvesting
    completes.

    `corpus.build_manifest` hashes the RAW FILE BYTES of `samples.jsonl`
    (`hashlib.sha256(samples_path.read_bytes())` -- verified by reading
    `corpus.py` directly, not assumed). Under `ThreadPoolExecutor`
    concurrency, which thread's write lands first is a scheduling accident,
    not reproducible run to run -- so two `reharvest_samples` calls that
    accept the exact same SET of samples could still produce different raw
    bytes, and therefore different `samples_sha256`. Sorting the raw
    JSON-line TEXT (never a parsed-then-re-serialized re-encoding, which
    could silently reorder a dict field's own keys) is what makes the byte
    content -- and therefore the hash -- depend on nothing but the accepted
    set itself.

    Runs ONLY on the success path (see `reharvest_samples`'s `try` block,
    called right after `stats["complete"] = True`): a partial file left by
    a crashed run is kept in whatever order it was written, which is more
    useful for resuming or debugging than a silently-reordered partial
    result.
    """
    lines = [ln for ln in samples_path.read_text().splitlines() if ln.strip()]
    lines.sort()
    samples_path.write_text("".join(ln + "\n" for ln in lines))
