"""Tests for the memory schema: episodic/semantic record shapes and content-addressed ids.

Every fixture below is written out literally -- no factory helper -- per the task brief:
these dataclasses are the interface every later S3 task (store, writer, retrieval,
falsification) constructs against, so the field list and its order need to be pinned by
values a reader can check by eye, not generated by a function that could quietly drift
out of sync with the dataclass itself.

``content_id``'s pinned digests are computed by hand (sha256 of
``json.dumps({"kind": kind, **identity_fields}, sort_keys=True)``) exactly the way
``test_units.py`` pins ``sha256_text("abc")`` -- a literal digest, not a recomputation of
the function under test.
"""

import json
from dataclasses import fields

from crucible.memory.schema import EpisodicRecord, SemanticItem, content_id, episode_verified

EPISODE = EpisodicRecord(
    item_id="1e5fa50fa4f297f13e8c9c088dd98301a5f1df6e297f59e928c162eee00d0b99",
    task_key="tk-abc123",
    arm="A_full",
    unit_id="HumanEval/12",
    family="ARITH",
    class_id="HumanEval/12|ARITH",
    phase=1,
    kind="first",
    root_prompt="Fix the bug in unit_humaneval_12.f so tests pass.",
    landed_module="def f(a, b):\n    return a + b\n",
    visible_reward=1.0,
    executions_charged=3,
    hidden_pass=True,
    verified=True,
    memory_item_ids=("sem-001", "sem-002"),
    created_at="2026-08-24T10:00:00Z",
    confidence=0.82,
    status="active",
    version=1,
    source_locator="run:pilot-a2/task:tk-abc123",
    valid_at="2026-08-24T10:00:00Z",
    invalid_at=None,
    expired_at=None,
    last_verified_at="2026-08-24T10:05:00Z",
    falsified_by=None,
    verification_method="hidden-suite",
)

SEMANTIC = SemanticItem(
    item_id="d84277bcfa8ae2a5989dfa92d5463acd9adbb2e1c6d1aa3441f925156f81df37",
    unit_id="HumanEval/12",
    family="ARITH",
    class_id="HumanEval/12|ARITH",
    cited_episode_id="ep-xyz789",
    mutated_spans=(((2, 5), (2, 9)),),
    landed_diff="-    return a - b\n+    return a + b\n",
    flipped_tests=("test_v0", "test_v1"),
    killing_tests=("test_v0",),
    created_at="2026-08-24T10:06:00Z",
    confidence=0.75,
    status="active",
    version=1,
    source_locator="run:pilot-a2/episode:ep-xyz789",
    valid_at="2026-08-24T10:06:00Z",
    invalid_at=None,
    expired_at=None,
    last_verified_at=None,
    falsified_by=None,
    verification_method="mechanical-template",
)

EPISODIC_FIELD_NAMES = {
    "item_id", "task_key", "arm", "unit_id", "family", "class_id", "phase", "kind",
    "root_prompt", "landed_module", "visible_reward", "executions_charged", "hidden_pass",
    "verified", "memory_item_ids", "created_at", "confidence", "status", "version",
    "source_locator", "valid_at", "invalid_at", "expired_at", "last_verified_at",
    "falsified_by", "verification_method",
}

SEMANTIC_FIELD_NAMES = {
    "item_id", "unit_id", "family", "class_id", "cited_episode_id", "mutated_spans",
    "landed_diff", "flipped_tests", "killing_tests", "created_at", "confidence", "status",
    "version", "source_locator", "valid_at", "invalid_at", "expired_at", "last_verified_at",
    "falsified_by", "verification_method",
}


def test_episodic_round_trips_through_json():
    r = EpisodicRecord.from_dict(json.loads(json.dumps(EPISODE.to_dict())))
    assert r == EPISODE


def test_semantic_round_trips_through_json():
    r = SemanticItem.from_dict(json.loads(json.dumps(SEMANTIC.to_dict())))
    assert r == SEMANTIC


def test_episodic_schema_is_complete():
    assert set(EPISODE.to_dict()) == {f.name for f in fields(EpisodicRecord)}
    assert set(EPISODE.to_dict()) == EPISODIC_FIELD_NAMES


def test_semantic_schema_is_complete():
    assert set(SEMANTIC.to_dict()) == {f.name for f in fields(SemanticItem)}
    assert set(SEMANTIC.to_dict()) == SEMANTIC_FIELD_NAMES


def test_content_id_is_the_sha256_of_kind_plus_identity_fields_sorted_keys():
    # Literal digest, not recomputed -- pins content_id to the hash it claims to be.
    assert (content_id("episode", {"task_key": "tk-abc123", "arm": "A_full"})
            == "1e5fa50fa4f297f13e8c9c088dd98301a5f1df6e297f59e928c162eee00d0b99")
    assert (content_id("semantic", {"cited_episode_id": "ep-xyz789"})
            == "d84277bcfa8ae2a5989dfa92d5463acd9adbb2e1c6d1aa3441f925156f81df37")


def test_content_id_is_stable_regardless_of_dict_insertion_order():
    forward = content_id("episode", {"task_key": "tk-abc123", "arm": "A_full"})
    reversed_order = content_id("episode", {"arm": "A_full", "task_key": "tk-abc123"})
    assert forward == reversed_order


def test_content_id_differs_when_an_identity_field_differs():
    a = content_id("episode", {"task_key": "tk-abc123", "arm": "A_full"})
    b = content_id("episode", {"task_key": "tk-abc123", "arm": "A_noMem"})
    assert a != b


def test_content_id_differs_when_kind_differs():
    # Same identity_fields dict, different kind: the two id spaces (episode vs semantic)
    # must not collide just because their identity fields happen to coincide.
    a = content_id("episode", {"task_key": "same-value"})
    b = content_id("semantic", {"task_key": "same-value"})
    assert a != b


def test_episode_verified_none_hidden_pass_is_not_verified():
    # None-vs-zero discipline: an episode that has not yet run its hidden suite is NOT
    # verified -- it must not be conflated with hidden_pass=False.
    assert episode_verified(None, False) is False


def test_episode_verified_true_but_tampered_is_not_verified():
    assert episode_verified(True, True) is False


def test_episode_verified_true_and_untampered_is_verified():
    assert episode_verified(True, False) is True


def test_episode_verified_false_hidden_pass_is_not_verified():
    assert episode_verified(False, False) is False
